logfile:      log.txt
owner:        discord_user_id
maxbrowsers:  10

ratelimit:
  increment:    2000
  peak:         3000

player:
  enabled:      true
  patrons:      false
  maxqueue:     50
  maxplaylist:  1

patrons:
  name:         "Your name"
  site:         "Patron Service Name"
  url:          patron_site_url
  guilds:
    - patron_guild_id
  users:
    - patron_user_id

discord:
  token:  your_token

reddit:
  timeout:      3600000
  cache-size:   100

youtube:
  token:        your_token

facebook:
  appid:  your_application_id
  secret: your_application_secret

statuses:
  - "a game"

mpstatus:
  interval:   60000
  timeout:    30000

filter:
  min:    2
  max:    20
  count:  25

settings:
  prefix:         "!"
  embed-mx:       true
  embed-titles:   true
  embed-maps:     true
  embed-forum:    true
  max-duration:   1800
  unit-convert:   false
  stalk-edits:    false
  limit-access:   false
  enable-filter:  true
  filter-admins:  false
  text-responses: true
  mocking-joy:    true