dommy:    99612832353505280

version:  "0.9.0"
vdate:    "2018-03-18"

discord:
  token:  your_token_here

youtube:
  token:  your_token_here

facebook:
  appid:  your_application_id
  secret: your_application_secret

logfile:  log.txt

statuses:
  - "a game"

mpstatus:
  interval:   60000
  timeout:    30000

filter:
  min:    2
  max:    20
  count:  25

settings:
  prefix:         "!"
  embed-mx:       true
  embed-titles:   true
  embed-maps:     true
  max-duration:   600
  unit-convert:   false
  stalk-edits:    false
  limit-access:   false
  enable-filter:  true
  filter-admins:  false
  text-responses: true
  mocking-joy:    true