dommy:    99612832353505280

discord:
  token:  your_token_here

youtube:
  token:  your_token_here

facebook:
  appid:  your_application_id
  secret: your_application_secret

settings:
  prefix:         '!'
  embed-mx:       true
  embed-titles:   true
  embed-maps:     true
  roles:          GalaxyBot
  max-duration:   600
  unit-convert:   true